### ISSUE TITLE
Change '?' to some other argument 

### ISSUE THREAD

**Issue by devx00** [panki27/minebash#2]
Some shells, such as ZSH, try to interpret certain characters, including the question mark, as wildcards. Changing the help argument to something like "-h" or "help" would avoid this issue. You can get around the issue by using quotes around the question mark, however a different argument would be cleaner.

**Comment by panki27** [comment]
Thanks for the information!
This has been impelemented in commit e4718c105bab855a24aaa9d514630df6b07095b8.
'minebash help'
